[package]
name = "aoc_2024"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "day1"
path = "src/day1.rs"

[[bin]]
name = "day2"
path = "src/day2.rs"

[dependencies]
util = { version = "0.1.0", path = "util" }
